Proyecto1/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    #path('', views.index, name="index"),
]

myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('productos/', views.lista_productos, name='lista_productos'),
    path('categorias/', views.lista_categorias, name='lista_categorias'),
    path('pedidos/', views.lista_pedidos, name='lista_pedidos'),
]

myapp/models.py
from django.db import models

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField()

    def __str__(self):
        return self.nombre
    
class Categoria(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()

    def __str__(self):
        return self.nombre
    
class Usuario(models.Model):
    nombre = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    fecha_registro = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre
    
class Pedido(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    fecha_pedido = models.DateTimeField(auto_now_add=True)
    total = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Pedido {self.id} - {self.usuario.nombre}"

myapp/views.py
from django.shortcuts import render
from .models import Producto, Categoria, Usuario, Pedido

# Create your views here.
def index(request):
    from datetime import datetime
    time_actual = datetime.now()
    contexto = {
        "mensaje": "Espero que aqui encuentres todo lo que necesitas. Aqui vas a encontrar todas las herramientas que necesites para que tu emprendimiento sea exitoso.",
        "time_actual": time_actual
    }
    return render(request, "myapp/index.html", context=contexto)
    

def lista_productos(request):
    productos = Producto.objects.all()
    contexto = {
        "productos": productos
    }
    return render(request, "myapp/lista_productos.html", context=contexto)

def lista_categorias(request):
    categorias = Categoria.objects.all()
    contexto = {
        "categorias": categorias
    }
    return render(request, "myapp/lista_categorias.html", context=contexto)

def lista_pedidos(request):
    pedidos = Pedido.objects.all()
    contexto = {
        "pedidos": pedidos
    }
    return render(request, "myapp/lista_pedidos.html", context=contexto)

myapp/templates/myapp/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My proyecto</title>
</head>
<body>
    {% block content %}
    
    
    {% endblock content %}
</body>
</html>

myapp/templates/myapp/index.html
{%  extends 'myapp/base.html' %} 

{% block tittle %}Inicio - My proyecto{% endblock tittle %}

{% block content %}
    <h1>Inicio</h1>

<nav>
    <a href="{% url 'myapp:index' %}">buscar</a>
    <a href="{% url 'myapp:index' %}">about</a>
</nav>

<h2>Informacion</h2>
<p>{{ mensaje }}</p>

<h2>Fecha de hoy</h2>
<p>{{ time_actual }}</p>


{% endblock content %}

myapp/templates/myapp/lista_categorias.html
{% extends 'myapp/base.html' %}

{% block title %}Lista de Productos - My proyecto{% endblock title %}

{% block content %}
    <h1>Lista de Categorias</h1>
    <ul>
        {% for categoria in categorias %}
            <li>{{ categoria }}</li>
        {% endfor %}
        </ul>
{% endblock content %}

myapp/templates/myapp/lista_pedidos.html
{% extends 'myapp/base.html' %}

{% block content %}
<h1>Lista de Productos</h1>

<ul>
    {% for pedido in pedidos %}
        <li>{{ pedido }}</li>
    {% endfor %}
</ul>

{% endblock content %}

myapp/templates/myapp/lista_productos.html
{% extends 'myapp/base.html' %}

{% block content %}
<h1>Lista de Productos</h1>

<ul>
    {% for producto in productos %}
        <li>{{ producto }}</li>
    {% endfor %}
</ul>

{% endblock content %}